[project]
name = "hyperviz-notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Frank Ligterink", email = "frank.ligterink@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datashader>=0.19.1",
    "holoviews>=1.23.1",
    "numpy>=2.4.6",
    "panel>=1.9.3",
]

[project.scripts]
hyperviz-notebooks = "hyperviz_notebooks:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "fairdatanow>=0.2.23",
    "ipykernel>=7.3.0",
    "jupyter-bokeh>=4.1.0",
    "jupytext>=1.19.5",
    "pip>=26.2.1",
]

[tool.jupytext]
formats = "ipynb,py:percent"
